version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jafo38583
      POSTGRES_PASSWORD: Alameda38583!
      POSTGRES_DB: conventioncrasher_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 